version: 2
jobs:
  build: &shared-config
    docker:
      - image: circleci/node:lts-fermium
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-v1
            - dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-v1

  lint:
    <<: *shared-config
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}-v1
      - run: yarn lint
      - run: yarn format:check

  back-test-unit:
    <<: *shared-config
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}-v1
      - run:
          command: yarn test
          environment:
            DATABASE_URL: postgres://$PG_USER:$PG_PASSWORD@localhost:5432/$PG_USER

  back-test-e2e:
    docker:
      - image: circleci/node:lts-fermium
      - image: circleci/postgres:9.6.5
        environment:
          POSTGRES_DB: $PG_USER
          POSTGRES_USER: $PG_USER
          POSTGRES_PASSWORD: $PG_PASSWORD
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}-v1
      - run:
          command: yarn test:e2e
          environment:
            DATABASE_URL: postgres://$PG_USER:$PG_PASSWORD@localhost:5432/$PG_USER

workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - lint:
          requires :
            - build
      - back-test-unit:
          requires:
            - build
      - back-test-e2e:
          requires:
            - build